baseURL = 'https://wang-xinkai.github.io/'
languageCode = 'en-us'
title = 'Xinkai Wang'
theme = "researcher"
publishDir="docs"
enableEmoji = true

[params]
  author = "Xinkai"
  description = "A simple monospaced resume theme for Hugo."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "By Xinkai Wang"
    url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "110px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "unbreakablewxk@sjtu.edu.cn"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "中文"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research"
    weight = 2
  [[menu.main]]
    name = "Publication"
    url = "/pub"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
